import { forwardRef } from "react";
import { Shield } from "lucide-react";

const CALC_LABELS = {
  "net-investment": "Net Investment Analysis",
  "barrels-to-cash": "Barrels to Cash Analysis",
  "natgas-to-cash": "Natural Gas to Cash Analysis",
  "rate-of-return": "Rate of Return Analysis",
  "tax-impact": "Tax Impact Analysis",
  "gold-purity": "Gold Purity Valuation",
  "ag-yield": "Agricultural Yield Projection",
  "metal-cost": "Metal Cost Basis Analysis",
  "livestock": "Livestock ROI Analysis",
};

/**
 * Branded card component for generating shareable calculator result images.
 * Rendered offscreen, captured via html2canvas.
 */
const ShareableResultCard = forwardRef(({ calcType, results }, ref) => {
  const calcLabel = CALC_LABELS[calcType] || "Calculator Results";

  // Extract up to 4 key result entries for display
  const resultEntries = results
    ? Object.entries(results)
        .filter(([, v]) => v !== null && v !== undefined && v !== "")
        .slice(0, 4)
        .map(([key, value]) => ({
          label: key
            .replace(/([A-Z])/g, " $1")
            .replace(/_/g, " ")
            .replace(/^\w/, (c) => c.toUpperCase())
            .trim(),
          value: typeof value === "number"
            ? value.toLocaleString("en-US", { maximumFractionDigits: 2 })
            : String(value),
        }))
    : [];

  return (
    <div
      ref={ref}
      style={{ width: 1200, height: 630, fontFamily: "system-ui, -apple-system, sans-serif" }}
      className="bg-gradient-to-br from-[#0a1929] via-[#0e2f55] to-[#1a3a6b] text-white p-12 flex flex-col justify-between"
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[#d4a843]/20 flex items-center justify-center">
            <Shield className="w-5 h-5 text-[#d4a843]" />
          </div>
          <span className="text-lg font-bold tracking-tight">
            <span className="text-[#d4a843]">Commodity</span> Investor<span className="text-[#d4a843]">+</span>
          </span>
        </div>
        <span className="text-sm text-white/40">commodityinvestor.app</span>
      </div>

      {/* Main content */}
      <div className="flex-1 flex flex-col justify-center py-8">
        <h2 className="text-3xl font-bold mb-8 text-[#d4a843]">{calcLabel}</h2>
        <div className="grid grid-cols-2 gap-6">
          {resultEntries.map((entry) => (
            <div key={entry.label} className="bg-white/5 rounded-xl p-5 border border-white/10">
              <p className="text-sm text-white/50 mb-1">{entry.label}</p>
              <p className="text-2xl font-bold text-white">{entry.value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between border-t border-white/10 pt-4">
        <span className="text-xs text-white/30">Generated by Commodity Investor+ | Not investment advice</span>
        <span className="text-xs text-[#d4a843] font-semibold">commodityinvestor.app</span>
      </div>
    </div>
  );
});

ShareableResultCard.displayName = "ShareableResultCard";

export default ShareableResultCard;
