import { createClientFromRequest } from 'npm:@base44/sdk@0.8.21';
import { jsPDF } from 'npm:jspdf@4.0.0';

const CALC_TITLES = {
  net_investment: "Net Investment Analysis",
  barrels_to_cash: "Oil Production Cash Flow Analysis",
  natgas_to_cash: "Natural Gas Cash Flow Analysis",
  rate_of_return: "Rate of Return Analysis",
};

function fmt(v) {
  if (v === null || v === undefined) return "N/A";
  return "$" + Number(v).toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}

function fmtPct(v) {
  if (v === null || v === undefined) return "N/A";
  return Number(v).toFixed(2) + "%";
}

function addHeader(doc, title, subtitle) {
  // Dark header bar
  doc.setFillColor(11, 37, 69); // petroleum
  doc.rect(0, 0, 210, 36, 'F');
  
  // Gold accent line
  doc.setFillColor(212, 168, 67); // crude-gold
  doc.rect(0, 36, 210, 1.5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("Commodity Investor+", 15, 14);
  
  doc.setFontSize(8);
  doc.setTextColor(180, 190, 210);
  doc.text("Professional Energy Investment Analysis", 15, 20);

  doc.setFontSize(14);
  doc.setTextColor(212, 168, 67);
  doc.text(title, 15, 30);

  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(180, 190, 210);
    doc.text(subtitle, 15, 35);
  }

  return 44; // Y position after header
}

function addSectionTitle(doc, y, title) {
  doc.setFillColor(240, 242, 245);
  doc.rect(12, y - 4, 186, 8, 'F');
  doc.setFontSize(10);
  doc.setTextColor(11, 37, 69);
  doc.text(title, 15, y + 1);
  return y + 12;
}

function addRow(doc, y, label, value, isHighlight = false) {
  if (isHighlight) {
    doc.setFillColor(212, 168, 67, 15);
    doc.rect(12, y - 3.5, 186, 7, 'F');
  }
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(label, 18, y);
  doc.setTextColor(11, 37, 69);
  doc.text(String(value), 195, y, { align: 'right' });
  return y + 8;
}

function addFooter(doc) {
  const pageHeight = doc.internal.pageSize.height;
  
  // Separator line
  doc.setDrawColor(220, 220, 220);
  doc.line(12, pageHeight - 25, 198, pageHeight - 25);
  
  doc.setFontSize(6.5);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "DISCLAIMER: This report is for informational and educational purposes only. It does not constitute investment, tax, or legal advice.",
    105, pageHeight - 20, { align: 'center', maxWidth: 180 }
  );
  doc.text(
    "All outputs are hypothetical and based on user-provided inputs. Oil and gas investments are speculative and involve risk of total loss.",
    105, pageHeight - 15, { align: 'center', maxWidth: 180 }
  );
  doc.text(
    `Generated by Commodity Investor+ on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} | commodityinvestor.app`,
    105, pageHeight - 10, { align: 'center', maxWidth: 180 }
  );
}

function buildNetInvestment(doc, inputs, results) {
  let y = addHeader(doc, CALC_TITLES.net_investment, `Total Investment: ${fmt(inputs.totalInvestment)}`);
  
  y = addSectionTitle(doc, y, "INPUT PARAMETERS");
  y = addRow(doc, y, "Total Investment Amount", fmt(inputs.totalInvestment));
  y = addRow(doc, y, "Federal Tax Bracket", fmtPct(inputs.federalTaxRate * 100));
  y = addRow(doc, y, "State Tax Rate", fmtPct(inputs.stateTaxRate * 100));
  y = addRow(doc, y, "Intangible Drilling Cost (IDC) %", fmtPct(inputs.idcPercentage * 100));
  y = addRow(doc, y, "Tangible Equipment %", fmtPct((1 - inputs.idcPercentage) * 100));
  
  y += 4;
  y = addSectionTitle(doc, y, "KEY RESULTS");
  y = addRow(doc, y, "Net Out-of-Pocket Investment", fmt(results.netInvestment), true);
  y = addRow(doc, y, "Effective Cost per Dollar Invested", (results.effectiveCost * 100).toFixed(1) + "¢");
  y = addRow(doc, y, "Total Year-1 Tax Savings", fmt(results.totalYear1TaxSavings), true);
  
  y += 4;
  y = addSectionTitle(doc, y, "TAX DEDUCTION BREAKDOWN");
  y = addRow(doc, y, "IDC Amount (100% Year-1 Deductible)", fmt(results.idcAmount));
  y = addRow(doc, y, "IDC Tax Savings", fmt(results.idcTaxSavings), true);
  y = addRow(doc, y, "Tangible Equipment Amount", fmt(results.tangibleAmount));
  y = addRow(doc, y, "Tangible Year-1 Depreciation (MACRS 14.29%)", fmt(results.tangibleDepreciation));
  y = addRow(doc, y, "Tangible Tax Savings (Year 1)", fmt(results.tangibleTaxSavings));
  
  y += 6;
  doc.setFillColor(212, 168, 67, 20);
  doc.rect(12, y - 3, 186, 18, 'F');
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.text("IRC §263(c): IDCs are 100% deductible in Year 1 for active working interest holders.", 18, y + 2);
  doc.text("Tangible costs depreciated under MACRS 7-year schedule (IRS Publication 946).", 18, y + 8);
  doc.text("15% Percentage Depletion (IRC §613A) applies during production phase — not shown above.", 18, y + 14);
  
  addFooter(doc);
}

function buildBarrelsToCash(doc, inputs, results) {
  let y = addHeader(doc, CALC_TITLES.barrels_to_cash, `${inputs.dailyBOPD} BOPD @ $${inputs.oilPrice}/bbl`);
  
  y = addSectionTitle(doc, y, "WELL PARAMETERS");
  y = addRow(doc, y, "Working Interest", fmtPct(inputs.workingInterest * 100));
  y = addRow(doc, y, "Net Revenue Interest", fmtPct(inputs.netRevenueInterest * 100));
  y = addRow(doc, y, "Daily Production", inputs.dailyBOPD + " BOPD");
  y = addRow(doc, y, "Oil Price", "$" + inputs.oilPrice + "/bbl");
  y = addRow(doc, y, "Lease Operating Expenses", "$" + inputs.loePerBbl + "/bbl");
  y = addRow(doc, y, "Severance Tax Rate", fmtPct(inputs.severanceTaxRate * 100));
  y = addRow(doc, y, "Annual Production Decline", fmtPct(inputs.declineRate * 100));
  
  y += 4;
  y = addSectionTitle(doc, y, "MONTHLY CASH FLOW SUMMARY");
  y = addRow(doc, y, "Your Gross Revenue (Month 1)", fmt(results.yourGross), true);
  y = addRow(doc, y, "Operating Expenses", fmt(results.operatingExpenses));
  y = addRow(doc, y, "Severance Tax", fmt(results.severanceTax));
  y = addRow(doc, y, "Net Monthly Income", fmt(results.netMonthly), true);
  y = addRow(doc, y, "Net Annual Income", fmt(results.netAnnual), true);
  
  // 5-Year table
  if (results.yearlyTable) {
    y += 4;
    y = addSectionTitle(doc, y, "5-YEAR PRODUCTION PROJECTION");
    
    // Table header
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Year", 18, y);
    doc.text("Daily Prod", 70, y, { align: 'center' });
    doc.text("Monthly Net", 120, y, { align: 'center' });
    doc.text("Annual Net", 170, y, { align: 'center' });
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(15, y, 195, y);
    y += 5;
    
    results.yearlyTable.forEach((row) => {
      doc.setFontSize(8.5);
      doc.setTextColor(40, 40, 40);
      doc.text("Year " + row.year, 18, y);
      doc.text(row.dailyProd + " BOPD", 70, y, { align: 'center' });
      doc.setTextColor(46, 125, 50);
      doc.text(fmt(row.monthlyNet), 120, y, { align: 'center' });
      doc.text(fmt(row.annualNet), 170, y, { align: 'center' });
      y += 7;
    });
  }
  
  addFooter(doc);
}

function buildNatGasToCash(doc, inputs, results) {
  let y = addHeader(doc, CALC_TITLES.natgas_to_cash, `${inputs.dailyMCF} MCF/day @ $${inputs.gasPrice}/MCF`);
  
  y = addSectionTitle(doc, y, "WELL PARAMETERS");
  y = addRow(doc, y, "Working Interest", fmtPct(inputs.workingInterest * 100));
  y = addRow(doc, y, "Net Revenue Interest", fmtPct(inputs.netRevenueInterest * 100));
  y = addRow(doc, y, "Daily Production", inputs.dailyMCF + " MCF/day");
  y = addRow(doc, y, "Gas Price", "$" + inputs.gasPrice + "/MCF");
  y = addRow(doc, y, "Gathering & Processing Fees", "$" + inputs.gatheringFee + "/MCF");
  y = addRow(doc, y, "Lease Operating Expenses", "$" + inputs.loePerMCF + "/MCF");
  y = addRow(doc, y, "Severance Tax Rate", fmtPct(inputs.severanceTaxRate * 100));
  y = addRow(doc, y, "Annual Production Decline", fmtPct(inputs.declineRate * 100));
  if (inputs.includeNGL) {
    y = addRow(doc, y, "NGL Yield", inputs.nglYield + " BBL/MCF");
    y = addRow(doc, y, "NGL Price", "$" + inputs.nglPrice + "/BBL");
  }
  
  y += 4;
  y = addSectionTitle(doc, y, "MONTHLY CASH FLOW SUMMARY");
  y = addRow(doc, y, "Your Gross Revenue (Month 1)", fmt(results.yourGross), true);
  if (inputs.includeNGL) {
    y = addRow(doc, y, "NGL Revenue (included above)", fmt(results.nglRevenue));
  }
  y = addRow(doc, y, "Gathering & Processing Fees", fmt(results.gatheringFees));
  y = addRow(doc, y, "Operating Expenses", fmt(results.operatingExpenses));
  y = addRow(doc, y, "Severance Tax", fmt(results.severanceTax));
  y = addRow(doc, y, "Net Monthly Income", fmt(results.netMonthly), true);
  y = addRow(doc, y, "Net Annual Income", fmt(results.netAnnual), true);
  
  if (results.yearlyTable) {
    y += 4;
    y = addSectionTitle(doc, y, "5-YEAR PRODUCTION PROJECTION");
    
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Year", 18, y);
    doc.text("Daily Prod", 70, y, { align: 'center' });
    doc.text("Monthly Net", 120, y, { align: 'center' });
    doc.text("Annual Net", 170, y, { align: 'center' });
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(15, y, 195, y);
    y += 5;
    
    results.yearlyTable.forEach((row) => {
      doc.setFontSize(8.5);
      doc.setTextColor(40, 40, 40);
      doc.text("Year " + row.year, 18, y);
      doc.text(row.dailyProd + " MCF/day", 70, y, { align: 'center' });
      doc.setTextColor(46, 125, 50);
      doc.text(fmt(row.monthlyNet), 120, y, { align: 'center' });
      doc.text(fmt(row.annualNet), 170, y, { align: 'center' });
      y += 7;
    });
  }
  
  addFooter(doc);
}

function buildRateOfReturn(doc, inputs, results) {
  const payoutLabel = results.isPaidOut ? `Payout: Month ${results.payoutMonth}` : "Not recovered in timeframe";
  let y = addHeader(doc, CALC_TITLES.rate_of_return, payoutLabel);
  
  y = addSectionTitle(doc, y, "INVESTMENT PARAMETERS");
  y = addRow(doc, y, "Net Investment Amount", fmt(inputs.netInvestment));
  y = addRow(doc, y, "Monthly Oil Income", fmt(inputs.monthlyOilIncome));
  y = addRow(doc, y, "Monthly Gas Income", fmt(inputs.monthlyGasIncome));
  y = addRow(doc, y, "Combined Monthly Income", fmt(inputs.monthlyOilIncome + inputs.monthlyGasIncome));
  y = addRow(doc, y, "Time Horizon", inputs.timeHorizon + " months");
  y = addRow(doc, y, "Annual Production Decline", fmtPct(inputs.annualDeclineRate * 100));
  
  y += 4;
  y = addSectionTitle(doc, y, "RETURN ANALYSIS");
  y = addRow(doc, y, "Total Revenue over Period", fmt(results.totalRevenue), true);
  y = addRow(doc, y, "Simple ROI", fmtPct(results.simpleROI));
  y = addRow(doc, y, "Internal Rate of Return (Annual)", results.annualIRR !== null ? fmtPct(results.annualIRR) : "N/A", true);
  y = addRow(doc, y, "Monthly Cash-on-Cash Yield", fmtPct(results.monthlyCashOnCash));
  y = addRow(doc, y, "Payout Period", results.isPaidOut ? `Month ${results.payoutMonth}` : "Not within timeframe");
  y = addRow(doc, y, "Simple Annualized Return", fmtPct(results.annualizedReturn));
  
  y += 6;
  doc.setFillColor(46, 125, 50, results.isPaidOut ? 15 : 0);
  if (!results.isPaidOut) doc.setFillColor(212, 168, 67, 20);
  doc.rect(12, y - 3, 186, 12, 'F');
  doc.setFontSize(10);
  doc.setTextColor(results.isPaidOut ? 46 : 180, results.isPaidOut ? 125 : 120, results.isPaidOut ? 50 : 0);
  doc.text(
    results.isPaidOut 
      ? `Investment pays out in Month ${results.payoutMonth} (${(results.payoutMonth / 12).toFixed(1)} years)`
      : "Investment does not pay out within the selected time horizon",
    105, y + 4, { align: 'center' }
  );
  
  addFooter(doc);
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { calcType, inputs, results } = await req.json();
    
    if (!calcType || !inputs || !results) {
      return Response.json({ error: 'Missing calcType, inputs, or results' }, { status: 400 });
    }

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    
    switch (calcType) {
      case 'net_investment':
        buildNetInvestment(doc, inputs, results);
        break;
      case 'barrels_to_cash':
        buildBarrelsToCash(doc, inputs, results);
        break;
      case 'natgas_to_cash':
        buildNatGasToCash(doc, inputs, results);
        break;
      case 'rate_of_return':
        buildRateOfReturn(doc, inputs, results);
        break;
      default:
        return Response.json({ error: 'Unknown calculator type' }, { status: 400 });
    }

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=EnergyCalc_${calcType}_${new Date().toISOString().split('T')[0]}.pdf`
      }
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return Response.json({ error: "Internal server error" }, { status: 500 });
  }
});