import { useState } from "react";
import { Shield, Lock, FileText, Scale, Eye, ChevronDown, ChevronUp, ExternalLink, AlertTriangle, Gavel, Users, Globe, CreditCard } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";

const LAST_UPDATED = "March 22, 2026";
const EFFECTIVE_DATE = "March 22, 2026";
const COMPANY_NAME = "EnergyCalc Pro";
const COMPANY_ENTITY = "EnergyCalc Pro, LLC";
const CONTACT_LEGAL = "legal@energycalcpro.com";
const CONTACT_PRIVACY = "privacy@energycalcpro.com";
const GOVERNING_STATE = "Texas";
const GOVERNING_COUNTY = "Harris County";

const sections = [
  {
    id: "master-disclaimer",
    icon: AlertTriangle,
    title: "Master Disclaimer & Nature of Services",
    priority: "critical",
    content: `PLEASE READ THIS SECTION CAREFULLY. BY ACCESSING OR USING THIS PLATFORM, YOU ACKNOWLEDGE AND AGREE TO THE FOLLOWING:

${COMPANY_NAME} (operated by ${COMPANY_ENTITY}) is a software-as-a-service ("SaaS") financial education and modeling platform. ${COMPANY_NAME} provides generalized financial calculators, educational content, and informational tools related to oil and gas investment structures.

${COMPANY_NAME} IS NOT AND DOES NOT ACT AS ANY OF THE FOLLOWING:
• A registered broker-dealer under the Securities Exchange Act of 1934
• A registered investment adviser under the Investment Advisers Act of 1940
• A certified public accountant ("CPA") or tax preparer
• A licensed attorney or provider of legal services
• A commodity trading advisor ("CTA") or commodity pool operator ("CPO") as defined by the Commodity Futures Trading Commission ("CFTC")
• A financial planner, financial counselor, or fiduciary of any kind
• A member of the Financial Industry Regulatory Authority ("FINRA")
• A registrant with the Securities and Exchange Commission ("SEC") or any state securities regulatory authority

${COMPANY_NAME} is not registered with, endorsed by, affiliated with, or supervised by FINRA, the SEC, the CFTC, the National Futures Association ("NFA"), the North American Securities Administrators Association ("NASAA"), or any state, federal, or international securities or commodities regulatory authority.

NOTHING ON THIS PLATFORM CONSTITUTES:
• Investment advice, whether personalized or general
• A solicitation, offer, or recommendation to buy, sell, hold, or otherwise transact in any security, commodity, futures contract, option, or financial instrument
• A securities offering or private placement under Regulation D, Regulation A, Regulation CF, or any other federal or state securities exemption
• Tax advice, tax planning, or tax preparation services
• Legal advice, legal analysis, or a legal opinion on any matter
• Accounting advice or financial statement analysis
• An endorsement or recommendation of any operator, fund, well, lease, offering, or investment opportunity
• A guarantee, projection, or prediction of future investment performance or returns

All outputs, calculations, projections, estimates, charts, and analyses generated by this platform are HYPOTHETICAL, ILLUSTRATIVE, AND FOR EDUCATIONAL PURPOSES ONLY. They are mathematical models based entirely on user-provided inputs and generalized assumptions. They do not represent actual investment results, historical performance, or guaranteed future outcomes.

OIL AND GAS INVESTMENTS ARE INHERENTLY SPECULATIVE AND INVOLVE A HIGH DEGREE OF RISK, INCLUDING BUT NOT LIMITED TO THE RISK OF TOTAL LOSS OF INVESTED CAPITAL. There is no guarantee that any oil or gas well will produce hydrocarbons in commercial quantities, or at all. Production rates, commodity prices, operating costs, regulatory environments, and tax laws are all subject to change without notice and can materially and adversely affect investment returns.

ANTI-RELIANCE STATEMENT
You acknowledge that you have not relied, and will not rely, upon any statement, representation, warranty, covenant, or agreement made by ${COMPANY_ENTITY} or any of the Released Parties, other than those expressly set forth in this Agreement, in making any decision regarding the use of this Platform or any investment decision. You have conducted, or will conduct, your own independent investigation and due diligence with respect to any investment opportunity. No oral or written information or advice given by ${COMPANY_ENTITY} or any of its representatives shall create any warranty or obligation not expressly stated herein.

IRS CIRCULAR 230 DISCLOSURE
TO ENSURE COMPLIANCE WITH REQUIREMENTS IMPOSED BY THE INTERNAL REVENUE SERVICE UNDER CIRCULAR 230 (31 C.F.R. PART 10), WE INFORM YOU THAT ANY U.S. FEDERAL TAX ADVICE CONTAINED IN THIS PLATFORM, INCLUDING BUT NOT LIMITED TO INFORMATION REGARDING INTANGIBLE DRILLING COSTS, PERCENTAGE DEPLETION, TANGIBLE EQUIPMENT DEPRECIATION, ACTIVE INCOME TREATMENT, AND OTHER TAX-RELATED CALCULATIONS AND CONTENT: (A) IS NOT INTENDED OR WRITTEN TO BE USED, AND CANNOT BE USED, FOR THE PURPOSE OF AVOIDING PENALTIES UNDER THE INTERNAL REVENUE CODE; (B) IS NOT INTENDED OR WRITTEN TO SUPPORT THE PROMOTION OR MARKETING OF ANY TRANSACTION OR MATTER ADDRESSED HEREIN; AND (C) EACH TAXPAYER SHOULD SEEK ADVICE BASED ON THE TAXPAYER'S PARTICULAR CIRCUMSTANCES FROM AN INDEPENDENT TAX ADVISOR.`
  },
  {
    id: "terms-of-use",
    icon: FileText,
    title: "Terms of Use Agreement",
    priority: "high",
    content: `Effective Date: ${EFFECTIVE_DATE}

ACCEPTANCE OF TERMS
By accessing, browsing, or using ${COMPANY_NAME} (the "Platform"), you ("User," "you," or "your") acknowledge that you have read, understood, and agree to be bound by these Terms of Use ("Terms"), the Privacy Policy, and all other policies and disclaimers posted on this Platform (collectively, the "Agreement"). If you do not agree to all terms of this Agreement, you must immediately cease using the Platform.

This Agreement constitutes a legally binding contract between you and ${COMPANY_ENTITY} ("Company," "we," "us," or "our"). Your continued use of the Platform after any modification to these Terms constitutes your acceptance of such modifications.

ELIGIBILITY
You must be at least eighteen (18) years of age and legally competent to enter into binding contracts in your jurisdiction to use this Platform. By using this Platform, you represent and warrant that you meet these eligibility requirements.

PERMITTED USE
The Platform is provided solely for your personal, non-commercial educational and informational purposes. You may use the calculators, educational content, and tools to enhance your personal understanding of oil and gas investment structures.

PROHIBITED USES — You expressly agree NOT to:
• Use this Platform or any output generated by it to solicit investors, market securities offerings, or raise capital from any person or entity
• Represent to any third party that any output from this Platform constitutes investment advice, a securities analysis, a legal opinion, tax advice, or a professional recommendation
• Use this Platform to provide investment advisory, broker-dealer, financial planning, tax preparation, or legal services to any third party, whether or not for compensation
• Reproduce, redistribute, sublicense, or commercially exploit any content, calculation output, educational material, or other intellectual property from this Platform without prior written consent
• Use the AI PPM Analyzer or any other AI-powered feature and represent or imply that its output constitutes legal review, a securities law opinion, or a substitute for review by a licensed securities attorney
• Use this Platform for any purpose that violates any applicable federal, state, local, or international law or regulation
• Attempt to gain unauthorized access to any portion of the Platform, its servers, or any systems connected to the Platform
• Use any automated system, scraper, bot, or similar technology to access the Platform for any purpose
• Interfere with or disrupt the Platform or any server, network, or system connected to the Platform

USER REPRESENTATIONS
By using this Platform, you represent and warrant that:
• You understand that oil and gas investments are speculative and involve substantial risk of loss
• You will not make investment decisions based solely on outputs from this Platform
• You will consult licensed professionals (including but not limited to registered investment advisers, licensed CPAs, and qualified attorneys) before making any investment decision
• All information you provide to the Platform is accurate and truthful
• You are using the Platform for your own personal educational purposes and not on behalf of any third party in a professional advisory capacity`
  },
  {
    id: "liability",
    icon: Shield,
    title: "Limitation of Liability & Disclaimer of Warranties",
    priority: "critical",
    content: `DISCLAIMER OF WARRANTIES
THE PLATFORM AND ALL CONTENT, TOOLS, CALCULATIONS, DATA, EDUCATIONAL MATERIALS, AI-GENERATED ANALYSES, AND SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ${COMPANY_ENTITY} EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:

• IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT
• WARRANTIES REGARDING THE ACCURACY, COMPLETENESS, RELIABILITY, TIMELINESS, OR AVAILABILITY OF ANY CONTENT OR TOOL ON THE PLATFORM
• WARRANTIES THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS
• WARRANTIES REGARDING THE RESULTS OBTAINED FROM USE OF THE PLATFORM
• WARRANTIES REGARDING THE ACCURACY OF ANY MARKET DATA, COMMODITY PRICES, TAX CALCULATIONS, PRODUCTION ESTIMATES, OR FINANCIAL PROJECTIONS

LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ${COMPANY_ENTITY}, ITS OWNERS, MEMBERS, MANAGERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, CONTRACTORS, AFFILIATES, LICENSORS, OR SERVICE PROVIDERS (COLLECTIVELY, THE "RELEASED PARTIES") BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY OF THE FOLLOWING, WHETHER ARISING OUT OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES:

• ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES
• LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITIES
• INVESTMENT LOSSES OF ANY KIND, INCLUDING BUT NOT LIMITED TO LOSSES ARISING FROM RELIANCE ON ANY CALCULATION, PROJECTION, ANALYSIS, MARKET DATA, OR EDUCATIONAL CONTENT PROVIDED ON OR THROUGH THE PLATFORM
• TAX LIABILITIES, PENALTIES, OR INTEREST ARISING FROM RELIANCE ON TAX-RELATED CALCULATIONS OR INFORMATION ON THE PLATFORM
• LOSSES ARISING FROM DECISIONS TO INVEST OR NOT TO INVEST IN ANY OIL AND GAS OPPORTUNITY, SECURITY, COMMODITY, OR FINANCIAL INSTRUMENT
• DAMAGES ARISING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA
• ANY OTHER LOSSES OR DAMAGES OF ANY NATURE WHATSOEVER

IN JURISDICTIONS THAT DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, OUR LIABILITY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.

AGGREGATE LIABILITY CAP
NOTWITHSTANDING ANYTHING TO THE CONTRARY, THE TOTAL AGGREGATE LIABILITY OF THE RELEASED PARTIES TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THE PLATFORM SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL AMOUNT YOU PAID TO ${COMPANY_ENTITY} IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED UNITED STATES DOLLARS ($100.00).`
  },
  {
    id: "assumption-of-risk",
    icon: AlertTriangle,
    title: "Assumption of Risk & Release",
    priority: "critical",
    content: `ASSUMPTION OF RISK
You expressly acknowledge and assume all risks associated with:

• The use of any financial calculator, modeling tool, or analytical feature on this Platform
• Any reliance on educational content, glossary definitions, FAQ responses, or AI-generated analyses provided on this Platform
• Investment decisions influenced in whole or in part by information obtained on or through this Platform
• The inherent speculative nature of oil and gas investments, including but not limited to dry hole risk, commodity price risk, operator default risk, regulatory risk, environmental risk, and liquidity risk
• The potential for total loss of invested capital in any oil and gas investment
• The use of AI-powered analysis tools, including the PPM Analyzer, which may produce inaccurate, incomplete, or misleading output
• Reliance on market data, commodity prices, or other third-party data displayed on the Platform, which may be delayed, estimated, or inaccurate

RELEASE OF CLAIMS
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU HEREBY IRREVOCABLY AND UNCONDITIONALLY RELEASE, WAIVE, AND FOREVER DISCHARGE THE RELEASED PARTIES FROM ANY AND ALL CLAIMS, DEMANDS, ACTIONS, SUITS, CAUSES OF ACTION, DAMAGES, LOSSES, COSTS, EXPENSES (INCLUDING ATTORNEYS' FEES), AND LIABILITIES OF EVERY KIND AND NATURE, WHETHER KNOWN OR UNKNOWN, SUSPECTED OR UNSUSPECTED, DISCLOSED OR UNDISCLOSED, THAT YOU HAVE, HAVE HAD, OR MAY IN THE FUTURE HAVE ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF THE PLATFORM.

IF YOU ARE A CALIFORNIA RESIDENT, YOU EXPRESSLY WAIVE THE PROTECTIONS OF CALIFORNIA CIVIL CODE SECTION 1542, WHICH PROVIDES: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS THAT THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE AND THAT, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY."

You understand that this release applies regardless of whether the damages or losses were caused in whole or in part by the negligence (but not the gross negligence or willful misconduct) of any of the Released Parties.`
  },
  {
    id: "indemnification",
    icon: Gavel,
    title: "Indemnification",
    priority: "high",
    content: `You agree to indemnify, defend, and hold harmless ${COMPANY_ENTITY} and the Released Parties from and against any and all claims, demands, actions, suits, proceedings, losses, damages, liabilities, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to:

• Your use of the Platform, including any output, calculation, or analysis generated through your use
• Your violation of any provision of this Agreement
• Your violation of any applicable federal, state, local, or international law, rule, or regulation
• Any representation or warranty made by you that proves to be untrue or misleading
• Any third-party claim arising from your use, reproduction, or distribution of any content or output from the Platform
• Any third-party claim that you used output from the Platform to provide investment advice, legal advice, tax advice, or other professional services
• Any investment decision made by you or any third party based in whole or in part on information obtained from the Platform
• Your use of the AI PPM Analyzer or any AI feature and any reliance by you or any third party on such output
• Any content, data, or information you submit to the Platform

This indemnification obligation shall survive the termination of your account and this Agreement. ${COMPANY_ENTITY} reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by you, and you agree to cooperate with our defense of such claims.`
  },
  {
    id: "arbitration",
    icon: Scale,
    title: "Dispute Resolution, Arbitration & Class Action Waiver",
    priority: "critical",
    content: `PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT AND TO HAVE A JURY TRIAL.

MANDATORY BINDING ARBITRATION
Any dispute, claim, or controversy arising out of or relating to this Agreement, the Platform, or your use of the Platform (collectively, "Disputes"), shall be resolved exclusively through final and binding arbitration administered by the American Arbitration Association ("AAA") under its Commercial Arbitration Rules then in effect, except as modified by this section.

• The arbitration shall be conducted by a single arbitrator with experience in software/technology disputes
• The arbitration shall be held in ${GOVERNING_STATE}, or at another location mutually agreed upon by the parties
• The arbitrator's decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction
• The arbitrator shall apply the substantive law of the State of ${GOVERNING_STATE} without regard to its conflict of laws provisions
• Each party shall bear its own costs and attorneys' fees, unless the arbitrator determines that a party's claims or defenses were frivolous, in which case the arbitrator may award costs and reasonable attorneys' fees to the prevailing party
• The arbitration proceedings and any award shall be confidential

EXCEPTIONS TO ARBITRATION
Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of intellectual property rights.

CLASS ACTION WAIVER
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. YOU EXPRESSLY WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION. If a court or arbitrator determines that this class action waiver is unenforceable as to a particular claim, then that claim (and only that claim) shall be severed from the arbitration and may be brought in a court of competent jurisdiction.

JURY TRIAL WAIVER
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU HEREBY KNOWINGLY, VOLUNTARILY, AND IRREVOCABLY WAIVE YOUR RIGHT TO A TRIAL BY JURY IN ANY ACTION, PROCEEDING, OR COUNTERCLAIM ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THE PLATFORM.

LIMITATION ON TIME TO FILE CLAIMS
ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE PLATFORM MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.

GOVERNING LAW
This Agreement and all Disputes shall be governed by and construed in accordance with the laws of the State of ${GOVERNING_STATE}, without giving effect to any choice or conflict of law provision or rule. To the extent any matter is not subject to arbitration under this Agreement, the exclusive jurisdiction and venue shall be in the state and federal courts located in ${GOVERNING_STATE}.`
  },
  {
    id: "ai-disclaimer",
    icon: Eye,
    title: "AI & Technology Disclaimer",
    priority: "high",
    content: `ARTIFICIAL INTELLIGENCE LIMITATIONS
${COMPANY_NAME} utilizes artificial intelligence ("AI") and machine learning technologies in certain features, including but not limited to the PPM Analyzer on the Investor Protection page, the Markets page AI-generated commentary, and certain educational content. You acknowledge and agree that:

• AI-generated output may contain errors, inaccuracies, omissions, or misleading information ("AI Hallucinations")
• AI output is NOT a substitute for professional legal, financial, tax, or investment advice from a licensed human professional
• AI analysis of PPM documents, offering materials, or other legal documents does NOT constitute legal review, a legal opinion, or securities law analysis
• No attorney-client, advisor-client, or fiduciary relationship is created by use of any AI feature on this Platform
• AI models are trained on historical data and may not reflect current laws, regulations, market conditions, or industry practices
• You assume all risk associated with any reliance on AI-generated output
• ${COMPANY_ENTITY} makes no representations or warranties regarding the accuracy, completeness, or reliability of AI-generated content

THIRD-PARTY DATA
Market data, commodity prices, and other financial data displayed on this Platform may be sourced from third-party providers. Such data may be delayed, estimated, approximate, or inaccurate. ${COMPANY_NAME} does not independently verify third-party data and makes no representations or warranties regarding its accuracy or timeliness. For trading or investment decisions, always consult official exchange data sources and licensed professionals.

TAX CALCULATION LIMITATIONS
Tax calculations provided by this Platform are based on generalized interpretations of the Internal Revenue Code as of the Platform's last content update. Tax laws, regulations, rulings, and interpretations change frequently. These calculations do not account for your specific tax situation, state and local taxes (which vary significantly), the Alternative Minimum Tax ("AMT"), phase-outs, or other individual factors that may materially affect your actual tax liability. ALWAYS CONSULT A LICENSED CPA OR TAX ATTORNEY WHO SPECIALIZES IN OIL AND GAS TAXATION BEFORE RELYING ON ANY TAX-RELATED OUTPUT.`
  },
  {
    id: "ip",
    icon: Lock,
    title: "Intellectual Property",
    priority: "standard",
    content: `OWNERSHIP
All content on this Platform — including but not limited to text, graphics, logos, icons, images, software, source code, calculators, financial models, educational content, glossary definitions, FAQ content, and all compilations thereof — is the exclusive property of ${COMPANY_ENTITY} or its licensors and is protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property laws.

The ${COMPANY_NAME} name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of ${COMPANY_ENTITY}. You may not use such marks without our prior written permission.

LICENSE TO USE
Subject to your compliance with this Agreement, ${COMPANY_ENTITY} grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Platform for your personal, non-commercial educational purposes.

RESTRICTIONS
You may not: (a) copy, modify, distribute, sell, lease, or create derivative works based on the Platform or its content; (b) reverse engineer, decompile, or disassemble any software component of the Platform; (c) remove, alter, or obscure any proprietary notices on the Platform; (d) use the Platform's content to train, develop, or improve any AI model, machine learning system, or competing product without express written consent.

DMCA NOTICE
If you believe that content on this Platform infringes your copyright, please send a DMCA takedown notice to ${CONTACT_LEGAL} with: (1) identification of the copyrighted work; (2) identification of the allegedly infringing material; (3) your contact information; (4) a statement of good faith belief; (5) a statement of accuracy under penalty of perjury; and (6) your physical or electronic signature.`
  },
  {
    id: "payment-terms",
    icon: CreditCard,
    title: "Subscription & Payment Terms",
    priority: "standard",
    content: `SUBSCRIPTION PLANS
${COMPANY_NAME} offers subscription-based access to premium features ("Subscription Plans") and one-time consulting service purchases. By subscribing to a plan or making a purchase, you agree to pay the applicable fees as described at the time of purchase.

PAYMENT PROCESSING
All payments are processed securely through Stripe, Inc. ("Stripe"), a PCI-DSS Level 1 certified payment processor. ${COMPANY_ENTITY} does not store your credit card number, debit card number, or bank account information on its servers. Your payment information is subject to Stripe's Privacy Policy and Terms of Service.

RECURRING BILLING
Subscription Plans are billed on a recurring monthly basis. Your subscription will automatically renew at the end of each billing period at the then-current rate unless you cancel prior to the renewal date. You authorize ${COMPANY_ENTITY} to charge the payment method on file for each renewal period.

CANCELLATION
You may cancel your subscription at any time. Cancellation will take effect at the end of the current billing period. You will retain access to premium features until the end of your paid period. No prorated refunds will be issued for partial billing periods.

REFUND POLICY
Subscription fees are generally non-refundable. For one-time consulting service purchases, refund eligibility is determined on a case-by-case basis. Contact ${CONTACT_LEGAL} within seven (7) days of purchase for refund inquiries.

PRICE CHANGES
${COMPANY_ENTITY} reserves the right to change subscription pricing at any time. We will provide at least thirty (30) days' notice of any price increase to existing subscribers. Continued use of the Platform after a price change constitutes your acceptance of the new pricing.

NO INVESTMENT RETURNS
For the avoidance of all doubt: subscription fees and consulting service payments are compensation for access to the ${COMPANY_NAME} SaaS platform and advisory consulting time, respectively. They are NOT investments, securities, promissory notes, or financial instruments of any kind. Subscription payments do not entitle you to any share of profits, returns, interest, dividends, or any other financial return.`
  },
  {
    id: "privacy",
    icon: Lock,
    title: "Privacy Policy",
    priority: "standard",
    content: `Effective Date: ${EFFECTIVE_DATE}

This Privacy Policy describes how ${COMPANY_ENTITY} ("we," "us," or "our") collects, uses, discloses, and protects your personal information when you use ${COMPANY_NAME} (the "Platform").

INFORMATION WE COLLECT
We collect information in the following categories:

Information You Provide Directly:
• Account registration data: name and email address
• Calculation inputs that you explicitly choose to save to your account
• User preferences (e.g., theme settings, display preferences)
• Communications you send to us (support requests, feedback)

Information Collected Automatically:
• Device information (browser type, operating system)
• Usage data (pages visited, features used, time spent)
• IP address (for security and fraud prevention)
• Cookies and similar tracking technologies

INFORMATION WE DO NOT COLLECT
We do not collect or store:
• Social Security numbers or tax identification numbers
• Bank account numbers, credit card numbers, or financial account information (payments are processed directly by Stripe)
• Investment portfolio data, brokerage account information, or net worth data
• Data entered into calculators that you do not explicitly save (unsaved calculations are processed in your browser and are not transmitted to our servers)

HOW WE USE YOUR INFORMATION
We use collected information to:
• Provide, maintain, and improve the Platform
• Process your account registration and manage your subscription
• Maintain your saved calculations and scenarios
• Send service-related communications (account notices, security alerts, feature updates)
• Analyze aggregate usage patterns to improve functionality
• Comply with legal obligations and enforce our Terms of Use
• Detect, prevent, and address fraud, security issues, and technical problems

We do NOT use your information to:
• Sell, rent, or trade your personal information to third parties for marketing purposes
• Profile you for targeted advertising
• Make investment recommendations or provide personalized financial advice
• Share your data with oil and gas operators, fund managers, or investment promoters

INFORMATION SHARING
We may share your personal information only in the following limited circumstances:
• Service Providers: With third-party vendors (e.g., Stripe for payment processing, hosting providers) who need access to perform services on our behalf, subject to contractual data protection obligations
• Legal Requirements: When required by law, subpoena, court order, or government regulation
• Safety: When necessary to protect the safety, rights, or property of ${COMPANY_ENTITY}, our users, or the public
• Business Transfers: In connection with a merger, acquisition, or sale of assets, with appropriate notice to users

DATA RETENTION
We retain your personal information for as long as your account is active or as needed to provide services. Upon account deletion request, we will delete your personal data within thirty (30) days, except where retention is required by law or for legitimate business purposes (e.g., fraud prevention, legal compliance).

DATA SECURITY
We implement industry-standard security measures including encryption in transit (TLS/SSL), secure authentication, and access controls. However, no method of internet transmission or electronic storage is 100% secure. We cannot guarantee absolute security of your data and accept no liability for unauthorized access resulting from factors beyond our reasonable control.

YOUR RIGHTS
Depending on your jurisdiction, you may have the right to:
• Access the personal data we hold about you
• Correct inaccurate personal data
• Delete your personal data ("right to be forgotten")
• Restrict or object to processing of your personal data
• Data portability (receive your data in a structured, machine-readable format)
• Withdraw consent at any time (where processing is based on consent)

To exercise any of these rights, contact ${CONTACT_PRIVACY}. We will respond to verifiable requests within thirty (30) days.

CALIFORNIA RESIDENTS (CCPA/CPRA)
If you are a California resident, you have additional rights under the California Consumer Privacy Act as amended by the California Privacy Rights Act, including:
• Right to know what personal information is collected, used, and disclosed
• Right to delete personal information
• Right to correct inaccurate personal information
• Right to opt out of the sale or sharing of personal information (we do NOT sell or share your personal information as defined by the CCPA/CPRA)
• Right to non-discrimination for exercising your privacy rights

To exercise your CCPA/CPRA rights, contact ${CONTACT_PRIVACY} or submit a verifiable consumer request.

CHILDREN'S PRIVACY
The Platform is not directed at persons under eighteen (18) years of age. We do not knowingly collect personal information from minors. If we become aware that we have collected personal information from a person under 18, we will promptly delete such information.

INTERNATIONAL USERS
The Platform is operated from the United States. If you access the Platform from outside the United States, you consent to the transfer of your information to the United States, which may have different data protection laws than your jurisdiction.

CHANGES TO THIS PRIVACY POLICY
We may update this Privacy Policy from time to time. We will notify registered users of material changes via email at least thirty (30) days before the changes take effect. The "Effective Date" at the top of this policy indicates when it was last revised. Your continued use of the Platform after changes take effect constitutes your acceptance of the revised policy.`
  },
  {
    id: "regulatory",
    icon: Scale,
    title: "Regulatory Compliance Disclosures",
    priority: "high",
    content: `SECURITIES LAW COMPLIANCE
${COMPANY_NAME} does not participate in the offer, sale, distribution, negotiation, or solicitation of any security, including but not limited to working interests, royalty interests, overriding royalty interests, net profits interests, promissory notes, limited partnership interests, LLC membership interests, or any other interest that may constitute a "security" as defined by Section 2(a)(1) of the Securities Act of 1933 and interpreted by the United States Supreme Court in SEC v. W.J. Howey Co., 328 U.S. 293 (1946).

The Investor Protection Center on this Platform is purely educational content designed to help individual investors identify common risk factors in private placement memoranda ("PPMs"), joint venture agreements, and other offering documents. The information presented does not evaluate, endorse, or pass upon the merits of any specific securities offering, and does not constitute a securities analysis or investment recommendation under any federal or state law.

INVESTMENT ADVISERS ACT OF 1940
${COMPANY_NAME} does not provide "investment advice" as defined by Section 202(a)(11) of the Investment Advisers Act of 1940. The Platform provides generalized financial calculators and educational materials that do not take into account any individual user's financial situation, investment objectives, risk tolerance, or specific circumstances. No fiduciary duty is created between ${COMPANY_ENTITY} and any user of this Platform.

FINRA RULE 2210 (COMMUNICATIONS WITH THE PUBLIC)
Although ${COMPANY_NAME} is not a FINRA member, our educational content is designed to be fair, balanced, and not misleading, consistent with the principles of FINRA Rule 2210. We do not: make performance guarantees; project specific investment returns without clearly labeling them as hypothetical and illustrative; omit material risks associated with oil and gas investments; or use misleading statistics or data to imply certain investment outcomes.

COMMODITY EXCHANGE ACT
${COMPANY_NAME} does not provide commodity trading advice, managed futures recommendations, or act as a commodity trading advisor ("CTA") or commodity pool operator ("CPO") as defined by the Commodity Exchange Act and CFTC regulations. Commodity price data displayed on this Platform is for informational purposes only and should not be used as the sole basis for commodity trading decisions.

STATE SECURITIES LAWS (BLUE SKY LAWS)
This Platform does not offer, sell, solicit, or facilitate the purchase of any securities in any state or jurisdiction. Content on this Platform does not constitute a securities offering under any state's Blue Sky laws. Users are responsible for compliance with the securities laws of their respective states.

ANTI-MONEY LAUNDERING (AML)
${COMPANY_ENTITY} does not accept, hold, transfer, or facilitate the transfer of investment funds or securities. ${COMPANY_NAME} is a SaaS platform that charges subscription fees for software access. We are not a financial institution subject to Bank Secrecy Act reporting requirements; however, we cooperate fully with law enforcement when legally required.

TAX DISCLAIMER
Tax-related calculations and information on this Platform are based on generalized interpretations of the Internal Revenue Code and Treasury Regulations as of the date of the Platform's most recent content update. This information does not constitute tax advice within the meaning of Treasury Department Circular 230. Users may not rely on tax-related information from this Platform for the purpose of avoiding tax penalties. Consult a licensed CPA or tax attorney for advice specific to your circumstances.`
  },
  {
    id: "miscellaneous",
    icon: Globe,
    title: "General Provisions",
    priority: "standard",
    content: `ENTIRE AGREEMENT
This Agreement (including the Terms of Use, Privacy Policy, and all disclaimers) constitutes the entire agreement between you and ${COMPANY_ENTITY} with respect to your use of the Platform and supersedes all prior or contemporaneous communications, proposals, and agreements, whether oral or written.

SEVERABILITY
If any provision of this Agreement is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction or arbitrator, such provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, shall be severed from this Agreement. The remaining provisions shall continue in full force and effect.

WAIVER
The failure of ${COMPANY_ENTITY} to enforce any right or provision of this Agreement shall not constitute a waiver of that right or provision. Any waiver must be in writing and signed by an authorized representative of ${COMPANY_ENTITY}.

ASSIGNMENT
You may not assign or transfer this Agreement or any rights hereunder without the prior written consent of ${COMPANY_ENTITY}. ${COMPANY_ENTITY} may assign this Agreement without restriction.

FORCE MAJEURE
${COMPANY_ENTITY} shall not be liable for any failure or delay in performance resulting from causes beyond its reasonable control, including but not limited to acts of God, natural disasters, pandemic, war, terrorism, government actions, power failures, internet disruptions, or third-party service provider failures.

NOTICES
All legal notices to ${COMPANY_ENTITY} must be sent to ${CONTACT_LEGAL}. Notices to you will be sent to the email address associated with your account.

SURVIVAL
The following sections shall survive termination of this Agreement: Master Disclaimer, Limitation of Liability, Assumption of Risk, Indemnification, Dispute Resolution, Intellectual Property, and General Provisions.

HEADINGS
Section headings are for convenience only and shall not affect the interpretation of this Agreement.

NO THIRD-PARTY BENEFICIARIES
This Agreement does not create any third-party beneficiary rights in any person or entity, except as expressly stated herein.

CONSTRUCTION
This Agreement shall not be construed against ${COMPANY_ENTITY} merely because ${COMPANY_ENTITY} drafted it. Both parties have had the opportunity to review these terms.`
  },
];

const priorityStyles = {
  critical: "border-l-4 border-l-flare-red",
  high: "border-l-4 border-l-crude-gold",
  standard: "",
};

function Section({ section }) {
  const [open, setOpen] = useState(false);
  const Icon = section.icon;
  return (
    <div className={`rounded-xl border border-border bg-card overflow-hidden ${priorityStyles[section.priority] || ""}`}>
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-3 px-5 py-4 hover:bg-muted/30 transition-colors text-left"
      >
        <div className="w-9 h-9 rounded-xl bg-primary/10 dark:bg-accent/10 flex items-center justify-center shrink-0">
          <Icon className="w-4 h-4 text-primary dark:text-accent" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-foreground">{section.title}</p>
          {section.priority === "critical" && (
            <Badge className="mt-1 bg-flare-red/10 text-flare-red border-flare-red/20 text-[9px] font-bold uppercase">Critical — Read Carefully</Badge>
          )}
        </div>
        {open ? <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0" /> : <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0" />}
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden border-t border-border"
          >
            <div className="px-5 py-5 space-y-3">
              {section.content.split("\n\n").map((para, i) => {
                const isHeading = /^[A-Z][A-Z &/()—,.'0-9]+$/.test(para.trim()) || /^[A-Z][A-Z &/()—,.'0-9]+:?$/.test(para.trim().replace(/:$/, ''));
                const isBulletBlock = para.includes("\n•") || para.startsWith("•");

                if (isBulletBlock) {
                  const lines = para.split("\n");
                  return (
                    <div key={i} className="space-y-1">
                      {lines.map((line, j) => {
                        if (line.startsWith("•")) {
                          return <p key={j} className="text-xs text-muted-foreground leading-relaxed pl-3">{line}</p>;
                        }
                        return <p key={j} className="text-xs text-muted-foreground leading-relaxed">{line}</p>;
                      })}
                    </div>
                  );
                }

                if (isHeading) {
                  return <p key={i} className="font-semibold text-foreground text-xs uppercase tracking-wide mt-5 first:mt-0 border-b border-border/50 pb-1.5">{para}</p>;
                }

                return <p key={i} className="text-xs text-muted-foreground leading-relaxed whitespace-pre-line">{para}</p>;
              })}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function Legal() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">

        {/* Header */}
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Shield className="w-5 h-5 text-primary dark:text-accent" />
            <h1 className="text-xl font-bold text-foreground">Legal Disclosures, Terms of Use &amp; Privacy Policy</h1>
          </div>
          <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>

        {/* Master Banner */}
        <div className="rounded-2xl border-2 border-flare-red/40 bg-flare-red/5 p-5">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-flare-red shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-bold text-flare-red uppercase tracking-widest mb-2">Important — Please Read Entire Document</p>
              <p className="text-sm text-foreground leading-relaxed font-medium">
                {COMPANY_NAME} is a financial education and SaaS modeling platform operated by {COMPANY_ENTITY}. It is <strong>not</strong> a registered broker-dealer, investment advisor, CPA firm, law firm, or fiduciary. Nothing on this platform constitutes investment advice, tax advice, legal advice, a securities offering, or a solicitation to invest. All calculations and analyses are hypothetical and illustrative only. Oil and gas investments are speculative and involve substantial risk, including total loss of capital. <strong>By using this platform, you agree to mandatory binding arbitration, a class action waiver, and all terms below.</strong>
              </p>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 mt-4">
            {["Not SEC Registered", "Not FINRA Member", "Not an Investment Advisor", "Not a CPA/Tax Firm", "Not a Law Firm", "Educational Use Only", "Binding Arbitration", "Class Action Waiver"].map(tag => (
              <span key={tag} className="text-[9px] font-bold uppercase tracking-wide px-2.5 py-1 rounded-full bg-flare-red/10 text-flare-red border border-flare-red/20">
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Table of Contents */}
        <div className="rounded-xl border border-border bg-card p-4">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Table of Contents</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
            {sections.map((s, i) => (
              <button
                key={s.id}
                onClick={() => {
                  const el = document.getElementById(`section-${s.id}`);
                  if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
                }}
                className="text-left text-xs text-muted-foreground hover:text-foreground transition-colors flex items-start gap-2 p-1.5 rounded-lg hover:bg-muted/30"
              >
                <span className="text-muted-foreground/60 font-mono">{String(i + 1).padStart(2, '0')}.</span>
                <span>{s.title}</span>
                {s.priority === "critical" && <span className="text-[8px] text-flare-red font-bold">●</span>}
              </button>
            ))}
          </div>
        </div>

        {/* All Sections */}
        <div className="space-y-3">
          {sections.map(section => (
            <div key={section.id} id={`section-${section.id}`}>
              <Section section={section} />
            </div>
          ))}
        </div>

        {/* Regulatory Links */}
        <div className="rounded-xl border border-border bg-card p-5">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Federal &amp; State Regulatory Resources</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {[
              { name: "SEC — Investor Education", url: "https://www.sec.gov/investor" },
              { name: "SEC EDGAR — Company Filings", url: "https://www.sec.gov/cgi-bin/browse-edgar" },
              { name: "FINRA — Investor Education", url: "https://www.finra.org/investors" },
              { name: "FINRA BrokerCheck", url: "https://brokercheck.finra.org/" },
              { name: "NASAA — State Securities Regulators", url: "https://www.nasaa.org/" },
              { name: "CFTC — Fraud Advisories", url: "https://www.cftc.gov/LearnAndProtect/index.htm" },
              { name: "IRS — Oil & Gas Tax Guidance", url: "https://www.irs.gov/businesses/small-businesses-self-employed/oil-and-gas-and-geothermal" },
              { name: "Texas RRC — Regulatory Filings", url: "https://www.rrc.texas.gov/" },
            ].map(link => (
              <a key={link.name} href={link.url} target="_blank" rel="noopener noreferrer"
                className="flex items-center gap-2 text-xs text-primary dark:text-accent hover:underline p-2 rounded-lg hover:bg-muted/30 transition-colors">
                <ExternalLink className="w-3.5 h-3.5 shrink-0" />
                {link.name}
              </a>
            ))}
          </div>
        </div>

        {/* Contact */}
        <div className="rounded-xl border border-border bg-muted/30 p-5">
          <p className="text-xs font-semibold text-foreground mb-2">Contact Information</p>
          <div className="space-y-1.5 text-xs text-muted-foreground">
            <p>Legal inquiries: <a href={`mailto:${CONTACT_LEGAL}`} className="text-primary dark:text-accent hover:underline font-medium">{CONTACT_LEGAL}</a></p>
            <p>Privacy requests: <a href={`mailto:${CONTACT_PRIVACY}`} className="text-primary dark:text-accent hover:underline font-medium">{CONTACT_PRIVACY}</a></p>
          </div>
        </div>

        {/* Version */}
        <div className="text-center text-[10px] text-muted-foreground/50 py-4">
          <p>{COMPANY_ENTITY} · Legal Document v3.0 · Effective {EFFECTIVE_DATE}</p>
          <p className="mt-1">This document was last reviewed and updated on {LAST_UPDATED}.</p>
        </div>

        {/* Navigation */}
        <div className="flex items-center justify-center gap-4 pb-4">
          <Link to="/" className="text-xs text-muted-foreground hover:text-foreground underline underline-offset-4">← Back to Home</Link>
          <Link to="/investor-protection" className="text-xs text-muted-foreground hover:text-foreground underline underline-offset-4">Investor Protection Center →</Link>
        </div>
      </div>
    </div>
  );
}